SELECT * FROM bank_loan_data

--1.
SELECT COUNT(ID) AS TOTAL_LOAN_APPLICATIONS FROM BANK_LOAN_DATA

--2.
SELECT COUNT(ID) AS TOTAL_LOAN_APPLICATIONS_MTD FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12 AND YEAR(ISSUE_DATE) = 2021

--3.
SELECT COUNT(ID) AS TOTAL_LOAN_APPLICATIONS_PMTD FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 11 AND YEAR(ISSUE_DATE) = 2021

--4.
WITH CTE AS (SELECT COUNT(CASE WHEN MONTH(ISSUE_DATE) = 12 THEN ID END) AS MTD,
COUNT(CASE WHEN MONTH(ISSUE_DATE) = 11 THEN ID END) AS PMTD
FROM bank_loan_data)
SELECT ROUND((MTD*1.0 - PMTD) /PMTD*100,2) AS MOM_GROWTH
FROM CTE

--5.
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan_data

--6.
SELECT SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12

--7.
SELECT SUM(LOAN_AMOUNT) AS PMTD_TOTAL_FUNDED_AMOUNT
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 11

--8.
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECIEVED
FROM bank_loan_data

--9.
SELECT SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECIEVED
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12

--10.
SELECT SUM(TOTAL_PAYMENT) AS PMTD_TOTAL_AMOUNT_RECIEVED
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 11

--11.
SELECT ROUND(AVG(INT_RATE*100),2) AS AVERAGE_INTEREST_RATE
FROM bank_loan_data

--12.
SELECT ROUND(AVG(INT_RATE*100),2) AS MTD_AVERAGE_INTEREST_RATE
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12

--13.
SELECT ROUND(AVG(INT_RATE*100),2) AS PMTD_AVERAGE_INTEREST_RATE
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 11

--14.
SELECT ROUND(AVG(DTI)*100,2) AS AVERAGE_DTI 
FROM bank_loan_data

--15.
SELECT ROUND(AVG(DTI)*100,2) AS MTD_AVERAGE_DTI 
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12

--16.
SELECT ROUND(AVG(DTI)*100,2) AS PMTD_AVERAGE_DTI 
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 11

--17.
SELECT 
(COUNT(CASE WHEN LOAN_STATUS IN ('Fully Paid','Current') THEN id end)*100)/
COUNT(ID) AS GOOD_LOAN_PERCENTAGE
from bank_loan_data

--18.
SELECT COUNT(ID) AS GOOD_LOAN_APPLICATIONS FROM bank_loan_data 
WHERE LOAN_STATUS IN ('Fully Paid','Current')

--19.
SELECT SUM(LOAN_AMOUNT) AS GOOD_LOAN_FUNDED_AMOUNT
FROM bank_loan_data
WHERE LOAN_STATUS IN ('Fully Paid','Current')

--20.
SELECT SUM(TOTAL_PAYMENT) AS GOOD_LOAN_RECIEVED_AMOUNT
FROM bank_loan_data
WHERE LOAN_STATUS IN ('Fully Paid','Current')

--21.
SELECT 
ROUND((COUNT(CASE WHEN LOAN_STATUS = 'Charged Off' THEN id end)*100)/
COUNT(ID),2) AS BAD_LOAN_PERCENTAGE
from bank_loan_data

--22.
SELECT COUNT(ID) AS BAD_LOAN_APPLICATIONS FROM bank_loan_data 
WHERE LOAN_STATUS = 'Charged Off'

--23.
SELECT SUM(LOAN_AMOUNT) AS BAD_LOAN_FUNDED_AMOUNT
FROM bank_loan_data
WHERE LOAN_STATUS = 'Charged Off'

--24.
SELECT SUM(TOTAL_PAYMENT) AS BAD_LOAN_RECIEVED_AMOUNT
FROM bank_loan_data
WHERE LOAN_STATUS = 'Charged Off'

--25.
SELECT LOAN_STATUS,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECIEVED,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
ROUND(AVG(INT_RATE*100),2) AS AVG_INT_RATE,
ROUND(AVG(DTI*100),2) AS AVG_DTI
FROM bank_loan_data
GROUP BY loan_status

--26.
SELECT LOAN_STATUS,
SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECIEVED,
SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT
FROM bank_loan_data
WHERE MONTH(ISSUE_DATE) = 12
GROUP BY LOAN_STATUS

--27.
SELECT MONTH(ISSUE_DATE) AS MONTH_NUMBER,
DATENAME(MONTH,ISSUE_DATE) AS MONTH_NAME,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY MONTH(ISSUE_DATE), DATENAME(MONTH,ISSUE_DATE)
ORDER BY MONTH(ISSUE_DATE)

--28.
SELECT ADDRESS_STATE,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY ADDRESS_STATE
ORDER BY SUM(LOAN_AMOUNT) DESC

--29.
SELECT TERM,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY TERM
ORDER BY TERM

--30.
SELECT EMP_LENGTH,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY EMP_LENGTH
ORDER BY EMP_LENGTH

--31.
SELECT PURPOSE,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY PURPOSE
ORDER BY SUM(LOAN_AMOUNT) DESC

--32.
SELECT HOME_OWNERSHIP,
COUNT(ID) AS TOTAL_APPLICATIONS,
SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_RECIEVED_AMOUNT
FROM bank_loan_data
GROUP BY HOME_OWNERSHIP
ORDER BY SUM(LOAN_AMOUNT) DESC